### ISSUE TITLE
Wildcard to block TLD (top-level domain)

### ISSUE THREAD

**Issue by TimBHowe** [hallme/gravityforms-emailblacklist#15]
A user requested the ability to block an entire top level domain with a wild card

Example *.ru would block all .ru domains emails addresses.

https://wordpress.org/support/topic/block-entire-domains-isp/

**Comment by TimBHowe** [comment]
Created a pull request for the feature and sent for first round of review.
https://github.com/hallme/gravityforms-emailblacklist/pull/17

**Comment by lwoods** [comment]
Sorry. I am confused.  Your "Info" for Email Addresses says "Domains."  Are you blocking email addresses or complete domains?

**Comment by TimBHowe** [comment]
In the case of this additional feature it allows the plugin to block a top level domain used in an email field. 

So for example if it is set to block '*.net' top level domain addresses, when some one tries using an email that ends in with the TLD, like for example 'robots@bot.net', that email would be prevented from submitting. Along with any other .net email addresses.

**Comment by omarc1492** [comment]
@TimBHowe Not working properly. Email blacklist entries are listed as a1yfcbobrov@outlook.com,bk.ru,*.ru,*.website,*.ua

Emails like the following are not caught and get submitted successfully
- tracytomm@freewebpages.website
- natali.borisenko.88@inbox.ru
- gavrilovaaniaubkl@mail.ua 

but the following are blocked from submitting
- asya.berestneva.77@bk.ru
- a1yfcbobrov@outlook.com

**Comment by ricky-poon** [comment]
@TimBHowe updated to v2.4 followed the instructions to add `*.ru, mail.ru`
`mail.ru` is block while `anythingelse.ru` goes through

**Comment by TimBHowe** [comment]
Sorry for the delay on a reply.

There was an issue where I didn't update all the versions numbers in the plugin. Please try deleting and reinstalling the plugin. 

Let me know if the issue still persists and I can take another look
